### ISSUE TITLE
Please add index_key

### ISSUE THREAD

**Issue by beth2016** [splunk/fluent-plugin-kubernetes-objects#31]
**What would you like to be added**:
index_key  -> which will specify the variable that contains the splunk index name
This is available in splunk-logging, but not in splunk-objects.

**Why is this needed**:
To be able to send different objects and events to different namespaces.

**Comment by chaitanyaphalak** [comment]
addresses in https://github.com/splunk/splunk-connect-for-kubernetes/issues/160
