### ISSUE TITLE
Please Provide Official v1.1.2 gem

### ISSUE THREAD

**Issue by jinghzhu** [splunk/fluent-plugin-kubernetes-objects#37]
Currently, for gem `fluent-plugin-kubernetes-objects`, we can only find following old versions:
```bash
$ gem search fluent-plugin-kubernetes-objects --all

*** REMOTE GEMS ***

fluent-plugin-kubernetes-objects (1.1.1, 1.1.0, 1.0.0)
```

As the [release v1.1.2](https://github.com/splunk/fluent-plugin-kubernetes-objects/releases/tag/1.1.2) is already available at June 27, can you please update it into the gem list?

Thanks in advance.

**Comment by jinghzhu** [comment]
@dtregonning @luckyj5 @gp510  @chaitanyaphalak

**Comment by chaitanyaphalak** [comment]
@jinghzhu it should be available now
