### ISSUE TITLE
Request for http_parser.rb dependency version upgrade

### ISSUE THREAD

**Issue by santhoshkvuda** [splunk/fluent-plugin-kubernetes-objects#90]
hi,
Could you relax the exact dependency on http_parser.rb version 0.5.3 ? It's very old version (released back in 2011) and the corresponding Git repo (submodules) is not compatible with recent changes from Git (w.r.t git protocol support). The request is to either relax the exact dependency or make version bumped to higher version available (0.8.0).
Thanks

**Comment by harshit-splunk** [comment]
I have bumped http_parser.rb to versuib 0.8.0

**Comment by santhoshkvuda** [comment]
Great, Thanks.
